[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python app_fixed.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
