[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "python3-dev", "python3-full", "gcc", "build-essential"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "/opt/venv/bin/pip install --no-cache-dir --upgrade pip",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python app_fixed.py"
