[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "gcc"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "python app_fixed.py"
